name: app
description: Flutter project template.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  camera: ^0.10.5+5
  dio: ^5.3.3
  dotlottie_loader: ^0.0.3
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_hooks: ^0.20.1
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.6
  freezed_annotation: ^2.2.0
  geolocator: ^10.1.0
  go_router: ^12.0.1
  google_maps_flutter: ^2.5.0
  hooks_riverpod: ^2.0.2
  image_gallery_saver: ^2.0.3
  lottie: ^2.7.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^1.10.24
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.2.1
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/icons/
